config/routes.rb
Ulegacy1::Application.routes.draw do

  devise_for :users
  root to: "pages#home"

  resources :legacies
 
  get '/about', to: 'pages#about' , as: :about
  get '/contact', to: 'pages#contact' , as: :contact

end

app/models/legacy.rb
class Legacy < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/legacies_controller.rb
class LegaciesController < ApplicationController

	def index
	end

	def new
		@legacy = Legacy.new
	end

	def create
	end

	def show
	end

	def destroy
	end

	def edit
	end

	def update
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def about
end

def contact
end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/legacies_helper.rb
module LegaciesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<html>
<head>
  <title>Ulegacy1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/legacies/new.html.erb
<div> new legacy | the legacy form will go here </div>




<%= form_for @legacy, html:{ role: "form", class: "new-legacy"} do |f| %>
  <% if @legacy.errors.any? %>
      <div id="error_explanation">
          <h1><%= pluralize(@legacy.errors.count, "error") %> prohibited this from being saved:</h1>

		      <ul>
			      <% @legacy.errors.full_messages.each do |msg| %>
			        	<li><%= msg %></li>
			      <% end %>
		      </ul>
      </div>
  <% end %>

			<div class="form-group">
			  <div class="field">
			    <%= f.label :First_Name %><br />
			    <%= f.text_field :first_name, class:"form-control", placeholder:"First Name" %>
			  </div>

			<div class="form-group">
			  <div class="field">
			    <%= f.label :Last_Name %><br />
			    <%= f.text_field :last_name, class:"form-control", placeholder:"Last Name"  %>  
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :Last_Name %><br />
			    <%= f.text_field :last_name, class:"form-control", placeholder:"Last Name"  %>
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :Last_Name %><br />
			    <%= f.text_field :last_name, class:"form-control", placeholder:"Last Name"  %>    
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :Address %><br />
			    <%= f.text_field :address, class:"form-control", placeholder:"Adress"  %>
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :City %><br />
			    <%= f.text_field :city, class:"form-control", placeholder:"City"  %>
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :State %><br />
			    <%= f.text_field :state, class:"form-control", placeholder:"State"  %>
			  </div>		    
		
			  <div class="form-group">
			  <div class="field">
			    <%= f.label :Zip_Code %><br />
			    <%= f.text_field :zip_code, class:"form-control", placeholder:"Zip Code"  %>
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :Gender %><br />
			    <%= f.text_field :gender, class:"form-control", placeholder:"Gender"  %>
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :DOB %><br />
			    <%= f.date_field :date_of_birth, class:"form-control", placeholder:"DOB"  %>  
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :Marital_Status %><br />
			    <%= f.text_field :gender, class:"form-control", placeholder:"Marital Status"  %>
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :Spouses_Name %><br />
			    <%= f.text_field :gender, class:"form-control", placeholder:"Spouses Name"  %>
			  </div>

			  <div class="form-group">
			  <div class="field">
			    <%= f.label :Legacy_Donations %><br />
			    <%= f.text_field :legacy_donations, class:"form-control", placeholder:"Legacy Donations"  %>
			  </div>

			  <div class="actions">
			    <%= f.submit class:"btn btn-default new-eurekamoment-button" %>
			  </div>
			  <% end %>

			</div>


   

app/views/legacies/show.html.erb
<div> Show page | This will show the created legacy after submitting it </div>

app/views/pages/about.html.erb
<div> About </div>

app/views/pages/contact.html.erb
<div> Contact </div>

app/views/pages/home.html.erb
<div> Home </div>

<%= link_to "Leave To Charity", new_legacy_path, class:"btn btn-default" %>